### ISSUE TITLE
[direct-client] ping/pong and timeout

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/rmb-sdk-go#5]
Direct client that connects and maintain an open connection to the relay need use the `ping/pong` message supported by the websocket to detect stalling connections. 

The idea is the relay is designed to reply PING messages from peers, which means a peer that is intended to maintain connection for a long time can use this to make sure of the following:
- send pings every 20 seconds to make sure underlying tcp connection does not time out 
  - also needed for any gateways in the way 
- each ping causes the server to reply with a pong message
- if the direct client does not receive pongs say in 2 or 3 times the ping interval means the connection is stalling and probably a reconnection is needed.

 the rust `rmb-peer` already does that to try to detect if the connection suddenly is stalling without the connection drop is detected by the system.

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/rmb_sdk_ts/issues/25#issuecomment-1479755916

The ping/pong was implemented and working without any issues.
