### ISSUE TITLE
[direct client] federation support

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/rmb-sdk-go#7]
Right now the direct client does not take federation into account. It simple sends the message with no federation information. Hence the relay then assumes that the destination twin just lives on the same relay. Instead the direct client needs to fill up the envelope federation information from the real twin data.

**Comment by mohamedamer453** [comment]
Verified from #8 

As mentioned above federation support was added and the direct client now contains the relay and twin information.
