### ISSUE TITLE
support e2e encryption for direct client

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/rmb-sdk-go#9]
we need to support e2e encryption in direct client, so things that uses direct client like terraform  be able to do deployments

**Comment by ashraffouda** [comment]
code is almost done but I have an issue the shared key is not same as generated in the peer

**Comment by ashraffouda** [comment]
done and merged

**Comment by mohamedamer453** [comment]
Verified from #22 

E2E support was [added](https://github.com/threefoldtech/rmb-sdk-go/blob/main/direct/direct.go#L104&L117) and it can be enabled or disabled while creating a new client object by setting the field to true or false as seen in the provided [example](https://github.com/threefoldtech/rmb-sdk-go/blob/main/examples/client_direct/main.go#L22).
